# Generated by Django 5.0.6 on 2024-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("middle_initial", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("month", models.CharField(max_length=255)),
                ("day", models.IntegerField()),
                ("year", models.IntegerField()),
                ("gender", models.CharField(max_length=255)),
                ("citizenship", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("zip", models.IntegerField()),
                ("country", models.CharField(max_length=255)),
                ("emergency_contact", models.CharField(max_length=255)),
                ("emergency_first_name", models.CharField(max_length=255)),
                ("emergency_last_name", models.CharField(max_length=255)),
                ("relationship", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=255)),
                ("language_list", models.CharField(max_length=255)),
                ("school_name", models.CharField(max_length=255)),
                ("graduation_date", models.DateField()),
                ("school_address", models.CharField(max_length=255)),
                ("school_city", models.CharField(max_length=255)),
                ("school_state", models.CharField(max_length=255)),
                ("payment_method", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
